name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Access Directory
      run: cd workshop-tonkotsu-nodejs
    - name: Run Build
      run: |
        cd workshop-tonkotsu-nodejs
        npm install
    - name: Run Tests
      run: npm test
